spring:
  application:
    name: product-service
  data:
    redis:
      port: 6379
      host: localhost
  datasource:
    username: postgres
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8087
